version: '3'

services:
  db:
    build:
      context: ./postgresql
      args:
        postgres_version: ${POSTGRES_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}-db
    command: ''
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_ROOT_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: ${TIMEZONE}
    volumes:
    - ./postgresql/dumps:/docker-entrypoint-initdb.d/:ro
    ports:
      - "5432:5432"

  web:
    build:
      context: ./odoo
      args:
        odoo_version: ${ODOO_VERSION}
    environment: 
        TZ: ${TIMEZONE}
        POSTGRES_DB: ${POSTGRES_DB}
        USER: ${POSTGRES_USER}
        PASSWORD: ${POSTGRES_PASSWORD}
    container_name: ${COMPOSE_PROJECT_NAME}-web
    volumes:
      - ./odoo/config:/etc/odoo
      - ./odoo/addons:/mnt/extra-addons
    ports:
      - "${ODOO_PORT}:8069"
    links:
      - db
